export const CHANGE_EDITOR_STATUS = "CHANGE_EDITOR_STATUS";
export const CHECK_PROD = "CHECK_PROD";
export const CHECK_ALL = "CHECK_ALL";
export const DELET_PRODS_SELECTED = "DELET_PRODS_SELECTED";
export const CANCEL_EDITOR = "CANCEL_EDITOR";
export const CHANGE_PROD_NUM = "CHANGE_PROD_NUM";
export const SAVE_PRODS_HISTORY = 'SAVE_PRODS_HISTORY';
export const BACK_PRODS_HISTORY = 'BACK_PRODS_HISTORY';